version: '2.4'
services:
  agent:
    build:
      context: .
    volumes:
      - agentmodel:/model
    image: cenotence/transformer
  train:
    ipc: host
    #runtime: nvidia
    command: "python /app/train.py"
    image: cenotence/transformer
    volumes:
      - ./data:/app/data
      - ./model:/model

  eval:
    #runtime: nvidia
    command: "python -u ./eval.py"
    image: cenotence/transformer
    volumes:
      - ./data:/app/data
      - ./model:/model
      - ./video:/app/video
      - ./image:/app/image
      - ./topdown:/app/topdown
      - ./topdown_scene_view:/app/topdown_scene_view
      - ./marged:/app/marged
      - ./Attention:/app/Attention
  train_restore:
    ipc: host
    #runtime: nvidia
    command: "python -u /app/train.py --restore"
    image: cenotence/transformer
    volumes:
      - ./data:/app/data
      - ./model:/model
volumes:
  agentmodel:

